language: python
os: linux
python:
  - 3.5
  - 3.6
  - 3.7
install:
    - pip install -r requirements.txt
    - pip install flake8 codecov
    - python setup.py build
    - python setup.py develop
    - pip install pytest-cov
script:
    - flake8 dca tests
    - pytest --cov=./ tests
after_success:
    - codecov
