name: DCA tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.8", "3.9"]
    steps:
      - name: Test DCA
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install flake8 codecov pytest-cov sphinx_rtd_theme
      - name: Lint with flake8
        run: |
          flake8 dca tests
      - name: Test with pytest
        run: |
          pytest -sv --cov=./ tests
      - name: Build docs
        run: |
          sphinx-build -W -b html docs/source docs/build
      - name: Codecov
        run: |
          codecov
